(defvar symbols-list '((empty " ")
		       (floor ".")
		       (player "@")
		       (entity "e")
		       (down-stair ">")
		       (up-stair "<")
		       (trap "^")
		       (item "?")
		       (wall "#")
		       (water "w")
		       (water-edge "_")
		       (boulder "B")
		       (door "[]")
		       (opened-door "||")
		       (tree-trunk "O")
		       (tree-branch-h "=")
		       (tree-branch-v "|")
		       ))
